### ISSUE TITLE
Enhancement: Support .snupkg packages format for symbols

### ISSUE THREAD

**Issue by estherthetesteramido** [Ensono/amido.github.io#23]
**Is your feature request related to a problem? Please describe.**
We are now publishing the https://github.com/amido/stacks-packages to Nuget.org. As part of this work, it was identified that there is bug in .NET Core 2.1 SDK which returns a 409 on trying to publish the symbols package. See [dotnet nuget push](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push) for more information.
When attempting to publish, we will get the following response:
`error: File does not exist (**/*.snupkg).`
In order to remedy this, we set the `--no-symbols` option. The symbols will then need to be published seperately. 

**Describe the solution you'd like**

 Package projects should be updated to target .Net Core 3.1. This will need to be released as a major version bump if not backwards compatible with .Net Core 2.2.

**Describe alternatives you've considered**
We are currently publishing without symbols to Nuget.org.

**Additional context**
Relates to https://github.com/amido/stacks/issues/1

**Comment by guibirow** [comment]
Have you consider changing the package output to `.snupkg` instead? As documented in the [nuget docs](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)

The packages target `.NetStandard` in order to be compatible with multiple versions of .Net Core and .Net Framework. We shouldn't pin the packages to a specific framework or core versions.

We don't intend intend to support older Framework and Core versions but we shouldn't limit the use in these if they are still compatible. What is a current version today will become old version in the future and breaking changes like this will give a bad experience to users of these packages.
